### ISSUE TITLE
Change Volume

### ISSUE THREAD

**Issue by Caindrac** [Gielert/NoodleJS#12]
Is it possible to change the volume on the fly? I have figured out how to add a audiofilter before the stream starts but would like to be able to change it after the audio is already playing.

**Comment by Gielert** [comment]
There is no way to change the volume on the fly yet. This feature was implemented in the pre 1.0 version. (https://github.com/Gielert/NoodleJS/blob/v0.0.9/lib/AudioStream.js#L33). This will then be used in the processAudioBuffer function (https://github.com/Gielert/NoodleJS/blob/v0.0.9/lib/AudioStream.js#L58)

It was the idea to implement this feature once again, but it got kind of on hold since I didn't have much time to maintain it again. I will check later if I have time, but in the meantime, feel free to make any adjustment necessary that meet your needs.

**Comment by Gielert** [comment]
Fixed in https://github.com/Gielert/NoodleJS/pull/13
