### ISSUE TITLE
Send Message does not work

### ISSUE THREAD

**Issue by Stateford** [Gielert/NoodleJS#3]
`Client.sendMessage()` does not work as intended.

I get an error stating message is not a function, probably has something to do with `lib/client.js`

not sure if this project is dead or not.

**Comment by Gielert** [comment]
I haven't checked on this for a while, because I haven't received any
issues since I posted this. I'll try to pick up on development as soon as
possible.

**Comment by Gielert** [comment]
Are you sending a message to a specific channel? Because the client.sendMessage requires a TextMessage object containing user/channel info. The client stores all channels in an array, so you should be able to use channel.sendMessage("your message", true/false). channel.sendMessage() uses the client.sendMessage() to write a message to the server, so client.sendMessage() should not be called directly. I'll update my documentation asap.

**Comment by Stateford** [comment]
``` js
client.on('textMessage', function(event) {
    event.textMessage.sender.channel.sendMessage('test, false');
    switch(event.textMessage.message) {
        // res/audio/donald/*
        case 'test':
            event.textMessage.sender.channel.sendMessage('foo', true);
            break;
    }
}
```

I'm trying this.

I'm not sure if he can't respond due to permissions due to certificate issues.

Is there a way to link certificates to the bot? It's not in the docs.

**Comment by Gielert** [comment]
There's currently no way to link certificates iirc. I tested your code and it seems to be working for me. The bot always connects insecure.
